/**
 * ============================================================
 * ROOTYM
 * File: lib/services/quote-pdf.service.ts
 * Sprint 8.1
 * ============================================================
 */

import type { Quote } from "@/lib/types/quote";

import {
  formatCurrency,
  formatDate,
} from "@/lib/utils/quote-format";

export interface QuotePdfDocument {
  fileName: string;

  mimeType: "application/pdf";

  html: string;
}

class QuotePdfService {
  /**
   * ------------------------------------------------------------
   * Generates HTML that can later be rendered by:
   *
   * • Puppeteer
   * • Playwright
   * • @react-pdf
   * • PDFKit
   * • IronPDF
   * ------------------------------------------------------------
   */

  async generate(
    quote: Quote
  ): Promise<QuotePdfDocument> {
    const html = this.buildHtml(
      quote
    );

    return {
      fileName: `${quote.quoteNumber}.pdf`,
      mimeType: "application/pdf",
      html,
    };
  }

  private buildHtml(
    quote: Quote
  ): string {
    const rows = quote.items
      .map(
        (item, index) => `
<tr>
<td>${index + 1}</td>
<td>${item.description ?? "-"}</td>
<td>${item.quantity}</td>
<td>${item.unit}</td>
<td>${formatCurrency(
          item.unitPrice,
          quote.currency as any
        )}</td>
<td>${formatCurrency(
          item.lineTotal,
          quote.currency as any
        )}</td>
</tr>`
      )
      .join("");

    return `
<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8"/>

<title>${quote.quoteNumber}</title>

<style>

body{
font-family:Arial,Helvetica,sans-serif;
padding:40px;
color:#222;
font-size:14px;
}

h1{
margin:0;
font-size:28px;
}

table{
width:100%;
border-collapse:collapse;
margin-top:25px;
}

th,td{
border:1px solid #ddd;
padding:10px;
}

th{
background:#f4f4f4;
text-align:left;
}

.summary{
margin-top:35px;
width:340px;
margin-left:auto;
}

.summary td{
padding:8px;
}

.footer{
margin-top:60px;
font-size:12px;
color:#777;
text-align:center;
}

</style>

</head>

<body>

<h1>ROOTYM</h1>

<p>
<b>Quotation:</b> ${quote.quoteNumber}<br/>
<b>Created:</b> ${formatDate(
      quote.createdAt
    )}<br/>
<b>Validity:</b> ${quote.validityDays} Days
</p>

<hr/>

<h2>Customer</h2>

<p>
${quote.companyName}<br/>
${quote.contactPerson}<br/>
${quote.email}
${
  quote.phone
    ? `<br/>${quote.phone}`
    : ""
}
${
  quote.country
    ? `<br/>${quote.country}`
    : ""
}
</p>

<table>

<thead>

<tr>
<th>#</th>
<th>Description</th>
<th>Qty</th>
<th>Unit</th>
<th>Unit Price</th>
<th>Total</th>
</tr>

</thead>

<tbody>

${rows}

</tbody>

</table>

<table class="summary">

<tr>

<td>Subtotal</td>

<td>${formatCurrency(
      quote.subtotal,
      quote.currency as any
    )}</td>

</tr>

<tr>

<td>Discount</td>

<td>${formatCurrency(
      quote.discount,
      quote.currency as any
    )}</td>

</tr>

<tr>

<td>Freight</td>

<td>${formatCurrency(
      quote.freight,
      quote.currency as any
    )}</td>

</tr>

<tr>

<td>Insurance</td>

<td>${formatCurrency(
      quote.insurance,
      quote.currency as any
    )}</td>

</tr>

<tr>

<td>Tax</td>

<td>${formatCurrency(
      quote.tax,
      quote.currency as any
    )}</td>

</tr>

<tr>

<th>Grand Total</th>

<th>${formatCurrency(
      quote.grandTotal,
      quote.currency as any
    )}</th>

</tr>

</table>

${
  quote.notes
    ? `
<h3>Notes</h3>

<p>${quote.notes}</p>
`
    : ""
}

<div class="footer">

Generated by ROOTYM Export Platform

</div>

</body>

</html>
`;
  }
}

export const quotePdfService =
  new QuotePdfService();